// <auto-generated />
namespace _09_shared_albums.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManyToManyAlbumsPhotographers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyToManyAlbumsPhotographers));
        
        string IMigrationMetadata.Id
        {
            get { return "201703131930345_ManyToManyAlbumsPhotographers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
