// <auto-generated />
namespace _01_local_store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedTableProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTableProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201703111034177_addedTableProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
